apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-resource-abstraction
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-resource-abstraction
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.16.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-nop
      version: "v0.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: "v0.7.0"